// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uzL7MLDrNkZiDQaUBve1wf
// Component: 7X73wCpmj9Ov

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_trust_pilot_clone.module.css"; // plasmic-import: uzL7MLDrNkZiDQaUBve1wf/projectcss
import sty from "./PlasmicButtonShare.module.css"; // plasmic-import: 7X73wCpmj9Ov/css

import ShareIcon from "./icons/PlasmicIcon__Share"; // plasmic-import: pQS1AqnA9AaB/icon

createPlasmicElementProxy;

export type PlasmicButtonShare__VariantMembers = {};
export type PlasmicButtonShare__VariantsArgs = {};
type VariantPropType = keyof PlasmicButtonShare__VariantsArgs;
export const PlasmicButtonShare__VariantProps = new Array<VariantPropType>();

export type PlasmicButtonShare__ArgsType = {};
type ArgPropType = keyof PlasmicButtonShare__ArgsType;
export const PlasmicButtonShare__ArgProps = new Array<ArgPropType>();

export type PlasmicButtonShare__OverridesType = {
  tagShare?: Flex__<"div">;
  svg?: Flex__<"svg">;
  labelShare?: Flex__<"div">;
};

export interface DefaultButtonShareProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicButtonShare__RenderFunc(props: {
  variants: PlasmicButtonShare__VariantsArgs;
  args: PlasmicButtonShare__ArgsType;
  overrides: PlasmicButtonShare__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"tagShare"}
      data-plasmic-override={overrides.tagShare}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.tagShare
      )}
    >
      <ShareIcon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(projectcss.all, sty.svg)}
        role={"img"}
      />

      <div
        data-plasmic-name={"labelShare"}
        data-plasmic-override={overrides.labelShare}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.labelShare
        )}
      >
        {"Share"}
      </div>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  tagShare: ["tagShare", "svg", "labelShare"],
  svg: ["svg"],
  labelShare: ["labelShare"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  tagShare: "div";
  svg: "svg";
  labelShare: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicButtonShare__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicButtonShare__VariantsArgs;
    args?: PlasmicButtonShare__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicButtonShare__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicButtonShare__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicButtonShare__ArgProps,
          internalVariantPropNames: PlasmicButtonShare__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicButtonShare__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "tagShare") {
    func.displayName = "PlasmicButtonShare";
  } else {
    func.displayName = `PlasmicButtonShare.${nodeName}`;
  }
  return func;
}

export const PlasmicButtonShare = Object.assign(
  // Top-level PlasmicButtonShare renders the root element
  makeNodeComponent("tagShare"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    labelShare: makeNodeComponent("labelShare"),

    // Metadata about props expected for PlasmicButtonShare
    internalVariantProps: PlasmicButtonShare__VariantProps,
    internalArgProps: PlasmicButtonShare__ArgProps
  }
);

export default PlasmicButtonShare;
/* prettier-ignore-end */
